import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="http://localhost:3000/auth/google">Login with Google</a>
      <a href="http://localhost:3000/auth/facebook">Login with Facebook</a>
      <a href="http://localhost:3000/auth/twitter">Login with Twitter</a>
      <a href="http://localhost:3000/auth/github">Login with Github</a>
      <a href="http://localhost:3000/auth/linkedin">Login with Linekdin</a>
    </div>
  );
}
