import Head from "next/head";
import styles from "../styles/Protected.module.scss";
import serverSideProps from "../functions/getServerSideProps";

export default function Protected({ user }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Protected</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      This page is protected. Your username is {user?.profile?.username}.
    </div>
  );
}

export const getServerSideProps = serverSideProps;
